KoolTheba/openssf-scorecard-api-visualizer

public/index.html, src/components/ProjectDetails.css, src/components/ProjectDetails.tsx, src/index.css
- Added the data visualization
- Added styles
- a5aca63 feat: added data to main component for visualization by @KoolTheba
- 56cb099 feat: improved styling by @KoolTheba
- c369b16 feat: improved details box with scrolling by @KoolTheba
=> feat: added data to main component for visualization

.github/workflows/deployment.yml, .github/workflows/pr_check.yml, .gitignore, README.md, package-lock.json, package.json, prettierrc.json, public/index.html, src/components/Error404.tsx, src/components/NotFound.tsx, src/components/ProjectDetails.css, src/components/ProjectDetails.tsx, src/index.css, src/index.tsx, src/reportWebVitals.ts, src/setupTests.ts, tsconfig.json
- Added Eslint and Prettier dependencies
- Added Prettier config and scripts
- Added CI pipeline
- 8fe71d0 chore: added dependencies  by @KoolTheba
- bd9fb91 chore: added prettier config by @KoolTheba
- 8e15894 chore: added npm scripts for linting and formatting by @KoolTheba
- ee257e1 chore: linting and formatting code by @KoolTheba
- 0a488c3 chore: added CI pipeline by @KoolTheba
- 2296aed chore: linting by @KoolTheba
- 286bc62 chore: extended gitignore rules by @KoolTheba
- cd1f8db chore: added CD pipeline by @KoolTheba
=> Feat: GitHub actions

package.json, src/index.tsx
- Added missing `homepage` metadata in `package.json` (0e767ca)
- Added support for Hash routes (70abd81)
- 0e767ca fix: added missing metadata in pkg by @UlisesGascon
- 70abd81 fix: added support for hashes routes by @UlisesGascon
=> Fix deployments

.github/workflows/scorecard.yml
- Added scorecard pipeline
- 765973a chore: added scorecard pipeline by @KoolTheba
=> chore: added scorecard pipeline

src/components/ProjectDetails.tsx
- Added StepSecurity link 
- b011bc7 Merge branch 'main' into feat/add-fix-score-tool-link by @KoolTheba
- 908e8aa feat: added StepSecurity link by @KoolTheba
=> Feat: added StepSecurity link

.github/workflows/dependency-review.yml, .github/workflows/scorecard.yml, src/components/ProjectCompartor.tsx, src/components/ProjectDetails.tsx, src/index.tsx
- Added component and route for comparator view 
- 09d8c3c feat: added route for comparator by @KoolTheba
- 3cdecae feat: added basic Comparator component by @KoolTheba
- bae9dbf lint: linting by @KoolTheba
=> Feat: added route and basic comparator 

src/components/ProjectCompartor.tsx, src/components/ProjectDetails.tsx, src/utils/getScorecardUrl.ts
- Added api calls for previous and current commit
- Moved `getScorecardUrl` as utility
- e667189 feat: added `getScorecardUrl` as utility by @KoolTheba
- daf119e feat: added api calls by @KoolTheba
=> Feat: comparator api calls

src/components/CommonError.tsx, src/components/Error404.tsx, src/components/ProjectCompartor.tsx, src/components/ProjectDetails.tsx, src/index.tsx
- Adapted Error components
- Added Error components to routes and main views
- 5f2d4e7 feat: improved components and error management by @KoolTheba
=> feat: improved components and error management

src/components/Badge.tsx, src/components/ProjectCompartor.tsx, src/components/ProjectDetails.tsx, src/styles/Badge.css, src/styles/ProjectDetails.css
- Added Badge component
- Added total score checker
- Moved style files to separate folder
- d587a43 feat: added Badge component and checker logic by @KoolTheba
=> feat: added Badge component and checker logic

src/components/ProjectCompartor.tsx, src/components/ProjectDetails.tsx, src/index.tsx, src/styles/ProjectDetails.css, src/types/index.ts, tsconfig.json
- Added logic for the details and reasoning (checks) comparator
- Improved styling
- Upgraded JS minimal version in `tsconfig`
- feefc35 feat: added error component to all routes as ErrorElement by @KoolTheba
- 5494528 feat: moved types to common file by @KoolTheba
- 8da1a0f chore: TS upgraded JS minimal version to ES6 by @KoolTheba
- d72949c feat: added comparator logic for details and reasoning by @KoolTheba
- 55f0076 feat: improved styling by @KoolTheba
=> Feat: comparator all score checks

src/components/Collapsable.tsx, src/components/ProjectCompartor.tsx, src/components/ProjectDetails.tsx, src/styles/Collapsable.css, src/styles/ProjectDetails.css
- Added Collapsible component for the comparator details' block
- 88faa2f feat: added Collapsable component and styles by @KoolTheba
- d483be0 feat: used new Collapsable in main components by @KoolTheba
=> Feat: added Collapsable component to the comparator details

src/components/ProjectCompartor.tsx, src/components/ProjectDetails.tsx, src/utils/formatDate.ts
- Close #35
- 38e0649 feat: improved date readability by @KoolTheba
=> feat: improved date readability

src/components/Loading.tsx, src/components/ProjectCompartor.tsx, src/components/ProjectDetails.tsx, src/styles/Badge.css, src/styles/Collapsable.css, src/styles/Loading.css, src/styles/ProjectDetails.css, src/utils/comparator/scoreChecker.tsx
- Moved Loading and utility code to individual files
- Improved styling for badge and others
- 8d69668 feat: improved badge visualization and other styling by @KoolTheba
- 0a08c39 lint: formatted by @KoolTheba
- 490da04 feat: moved loading and utility code to individual files by @KoolTheba
- 4e5f953 lint: formatted code by @KoolTheba
=> Feat: Improved styling for badge and others

src/components/CommonError.tsx, src/components/ProjectCompartor.tsx, src/constants/commonErrorMessage.ts
- Improved error management
- Added more specificity for errors depending on the view/interaction
- fcfdfda feat: improved error handling by @KoolTheba
=> feat: improved error handling

README.md
- 4dec312 docs: improved documentation by @KoolTheba
=> docs: improved documentation

cypress/e2e/visualizer.cy.ts, cypress/fixtures/50477fa35367bb76e5f56ac93d661b01a5578cec.json, cypress/fixtures/example.json, src/components/ProjectDetails.tsx, src/constants/commonErrorMessage.ts
- Added tests scenarios for the visualizer
- Added fixtures for commit Scorecard
- Improved error management
- Linted code
- 0480939 fix: fixed error range for http responses by @KoolTheba
- 758f415 test: added e2e test for visualizer by @KoolTheba
- ce4cd32 chore: linting by @KoolTheba
- 8737664 test: adapted common error message and test spec by @KoolTheba
- d6d580e test: added test ids to Project Detail component elements by @KoolTheba
- b3c8a83 test: added fixtures by @KoolTheba
- fb503cb test: added all tests scenarios for the visualizer tool by @KoolTheba
=> Feature: visualizer tests

cypress/e2e/comparator.cy.ts, cypress/fixtures/077fd7d83d7d41695137c1af5b9be1d72250e69e.json, cypress/fixtures/2ac5e9889aba461f5a54d320973d2574980d206b.json, src/components/ProjectCompartor.tsx
- Added fixtures, test ids and tests for comparator
- Refactored commit data handler for improved legibility
- Fixed minor issues
- 3c6f13f test: added fixtures for previous and current commit by @KoolTheba
- 9329ed9 test: added tests for comparator feature by @KoolTheba
- 06a1039 fix: removed unused error message by @KoolTheba
- 98475bd fix: fixed status for server error by @KoolTheba
- 9a3c547 feat: refactored data handler to improve legibility by @KoolTheba
- 0a760c3 test: added test ids by @KoolTheba
=> Test: added comparator tests

src/components/ComparatorDiff.tsx
- Close #177
- Changed the diff method for improving the visualization:
**BEFORE**
------------
**CURRENT**
--------------
- 4ea369d feat: added diff method for improving visualization by @KoolTheba
=> feat: added diff method for improving visualization

src/components/ProjectCompartor.tsx, src/components/ProjectDetails.tsx, src/constants/platforms.ts
- Related #152 
- 1d5d5c6 feat: added platform dinamically to commit links by @KoolTheba
- b4c6426 feat: added condition to step sec and deps dev links by @KoolTheba
=> Feat: adapted links to availability for gitlab

cypress/e2e/comparator.cy.ts, package-lock.json, package.json, src/components/ProjectComparator.tsx, src/utils/comparator/scoreChecker.tsx
=> chore: upgrade dependencies
